GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kyle",
  "email": "test@123",
  "password": "password"
}


###

POST http://localhost:3000/login
Content-Type: application/json

{
  "name": "Kyle",
  "email": "test@123",
  "password": "password"
}

